### ISSUE TITLE
xmondrian postgresql data source

### ISSUE THREAD

**Issue by bobdoss** [rpbouman/xmondrian#1]
Hi Roland,
Great work.  Thanks.  I am struggling with Mondrian releases and out of date documentation.
The xmondrain war file makes things so much easier.  
Would you please help me connect xmondrian to PostgreSQL?  I have Mondrian 3.5 samples in 3.5 (except for the XMLA ones) using Foodmart in PostgreSQL 9.5.  I've confirmed by turning PostgreSQL logging on.
This DataSourceInfo works in 3,5 in datasources.xml  
Provider=mondrian; Jdbc=jdbc:postgresql://localhost/Mondrian_Foodmart; JdbcDrivers=org.postgresql.Driver;JdbcUser=postgres;JdbcPassword=xxxx; Catalog=/WEB-INF/FoodMart.xml.
When I add the postgresql jdbc jar file and change the datasource.xml in xmondrian and use  Xavier or Xmlash it fails with: 
error SOAP-ENV:Server.00HSBE02: XMLA Discover unparse results error (source: _requestSuccess, actor: Mondrian) 00HSBE02: The Mondrian XML: Mondrian Error:Internal error: No suitable connection found.  I am testing with tomcat and windows 7.
Thanks in advance for any tips.
Cheers,
Bob Doss

**Comment by rpbouman** [comment]
Hi bobdoss! Thanks for your interest. 

I just tried myself, and I got it going pretty quicky. These are the steps I did:
- make sure your postgres is running. Create a role "foodmart" and a database "foodmart" using a tool like pgAdmin or so.
- download the zipped project from https://github.com/OSBI/foodmart-data (https://github.com/OSBI/foodmart-data/archive/master.zip)
- extract zip. You'll get a foodmart-data-master dir.
- Go into the "data" subdir, extract "DataScript.zip". Then copy "FoodMartCreateData.sql" from the extracted "DataScript" directory 2 levels up, so that it sits in "data/FoodMartCreateData.sql"
- cd into the main foodmart-data-master dir. Then run command according to instructions of the project:

sh FoodMartLoader.sh --db postgres

This sets up the database side of things.
- Now, stop your java web server where you deployed xmondrian
- download the postgres jdbc driver (I got mine here: https://jdbc.postgresql.org/download/postgresql-9.4.1208.jar) and store it in xmondrian\WEB-INF\lib
- Find xmondrian\WEB-INF\datasources.xml and make a copy so you can safely edit it.
- open datasources.xml in a text editor. 
- set the DataSourceInfo element to Provider=mondrian;Jdbc=jdbc:postgresql://localhost/foodmart;JdbcDrivers=org.postgresql.Driver;JdbcUser=postgres;JdbcPassword=postgres
- start your webserver

This gave me a functional foodmart on postgres with xmondrian.

I hope this helps, cheers!

**Comment by rpbouman** [comment]
Please let me know if I can close the issue. Best regards,

Roland

**Comment by bobdoss** [comment]
Hi Roland,
Thanks.  I worked it out. Please close the issue. I had to get the DataSourcesConfig in Web.xml set up correctly for windows path  to refer to datasources.xml.  And <servlet>
    <servlet-name>MondrianXmlaServlet</servlet-name>
    <servlet-class>mondrian.xmla.impl.DynamicDatasourceXmlaServlet</servlet-class>
    <init-param>
      <param-name>DataSourcesConfig</param-name>
      <param-value>file:///C:/catalina/webapps/mondrian3_5/WEB-INF/datasources.xml</param-value>
    </init-param>
  </servlet>
And then the datasources.xml seemed to need a relative path in catalogs definition.  
<DataSourceInfo>Provider=mondrian; Jdbc=jdbc:postgresql://localhost/FoodMart; JdbcDrivers=org.postgresql.Driver;JdbcUser=postgres;JdbcPassword=xxxxx</DataSourceInfo>
    <ProviderName>Mondrian</ProviderName>
    <ProviderType>MDP</ProviderType>
    <AuthenticationMode>Unauthenticated</AuthenticationMode>
    <Catalogs>
        <Catalog name="FoodMart">
            <Definition>/WEB-INF/schema/Foodmart.xml</Definition>
        </Catalog>
    </Catalogs>
  </DataSource>

**Comment by rpbouman** [comment]
Ok, cool! Always feel free to ask or let me  know how you get along with xmondrian or any of the bundled projects. Best regards, 

Roland

**Comment by mohammadSulaiman29** [comment]
please can you send a picture of code @bobdoss
