### ISSUE TITLE
How to update Xavier?

### ISSUE THREAD

**Issue by epoiate** [rpbouman/xmondrian#5]
Hello Roland! 
First, I would like to thank you because you are helping me immensely on my graduation.
I tried to to update the Xavier inside xmondrian with the new xavier.zip from it's repository, but now it doesn't recognize the datasource I specified in my datasource.xml file, a window opens instead and asks for the url of the xmla server. Is there a new configuration I'm missing? 

Since i'm already here, I just discovered your Pentaho Analysis Editor and it looks a lot nicer than the Schema Workbench that i'm currently using. Is it mandatory that I use it with Pentaho or can I use it with xmondrian?

Thank you again.

**Comment by rpbouman** [comment]
Hi epoiate, 

You can update xavier, just make sure the html page that forms the entrypoint is configured correctly for xmondrian. Just compare the index.html (or is it xavier.html?) that comes with xmondrian with the one that ships with xavier.

Phase (the schema editor) only works with pentaho, since it uses the web services (as well as pedis service) that runs on the pentaho platform.

**Comment by rpbouman** [comment]
xmondrian was just updated to include the latest version of xavier.
